# -*- coding: utf-8 -*-
"""Conexion_MongoDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1u2g9IZ33H_Q70_3exiBCtBVzAoRWJG
"""

!pip install pymongo

import pymongo

# Conexión a MongoDB Atlas con la cadena de conexión correcta
client = pymongo.MongoClient("mongodb+srv://juanfernandezsolaria:<password>@cluster0.f46tn.mongodb.net/")

# Accede a la base de datos
db = client["fotovoltaica_db"]

# Accede a la colección 'prueba_inicial'
collection = db["prueba_inicial"]

# Realiza una consulta para obtener todos los documentos
data = collection.find()

# Convierte los documentos a una lista de Python
data_list = list(data)

# Muestra los primeros 5 documentos
print(data_list[:5])

import pandas as pd

# Asumiendo que 'data_list' ya está definida y contiene los documentos de MongoDB

extracted_data = []

for document in data_list:
    for key, value in document.items():
        if isinstance(value, list) and key != '_id':  # Ignora el campo _id
            plant = key.split('.')[0]
            equip = key.split('.')[1]
            signal = key.split('.')[2]
            for item in value:
                extracted_data.append({
                    "Plant": plant,
                    "Equip": equip,
                    "Signal": signal,
                    "time": item["t"],
                    "valor": item["v"],
                    "quality": item["q"]
                })

df = pd.DataFrame(extracted_data)
